In [3]:
import pandas as pd
import numpy as np
import os #os.listdir()

In [5]:
ParentPath = r'G:\DataMining\project\data'

# Main

In [57]:
filelist = os.listdir(ParentPath)
filelist = pd.Series(filelist)
factlevel = ['false', 'half-true', 'mostly-false', 'mostly-true', 'pants-fire', 'true']
outlist = filelist.apply(lambda x: x[:-4])
colnames = ['Author', '1', 'Content', 'FactLevel']
print(len(filelist))
print(filelist)
print(outlist)

6
0           false.txt
1       half-true.txt
2    mostly-false.txt
3     mostly-true.txt
4      pants-fire.txt
5            true.txt
dtype: object
0           false
1       half-true
2    mostly-false
3     mostly-true
4      pants-fire
5            true
dtype: object

In [59]:
for i in range(len(filelist)):
    wholepath = ParentPath + '\\' + filelist[i]
    data = pd.read_csv(wholepath, header = None, sep = '\t', names = colnames)
    data['1'] = data['1'].apply(lambda x: x[11:])
    data['1'] = data['1'].apply(lambda x: x[:-2])
    df1 = data1['1'].str.split(r" in ", n = 1, expand=True)
    data1['Date'] = df1[0]
    df2 = data1['1'].str.split(r", ",n=1, expand=True)
    data['Occasion'] = df2[1].astype('str').apply(lambda x: x[8:])
    data = data.drop(columns=['1'])
    topath = ParentPath + '\\' + outlist[i] + '.csv'
    data.to_csv(topath)

# temp

In [11]:
# 1
wholepath = ParentPath + '\\' + 'false.txt'
colnames = ['Author', '1', 'Content', 'FactLevel']
data1 = pd.read_csv(wholepath, header = None, sep = '\t', names = colnames)
data1.head()

,Author,1,Content,FactLevel
0,Facebook posts,"stated on November 6, 2020 in a Facebook post:",“The NAACP has received credible information ...,false
1,Facebook posts,"stated on November 5, 2020 in an Instagram po...",An election worker in Georgia threw away a ba...,false
2,Tweets,"stated on November 5, 2020 in a tweet:","A list shows over 14,000 dead people voted in...",false
3,Nevada Republican Party,"stated on November 5, 2020 in a tweet:","Republicans in Nevada found “at least 3,062 i...",false
4,Ted Cruz,"stated on November 5, 2020 in a Fox News inte...",Philadelphia is “clouding the vote counting i...,false

In [18]:
data1['1'] = data1['1'].apply(lambda x: x[11:])

In [22]:
data1['1'] = data1['1'].apply(lambda x: x[:-2])

In [23]:
data1.head()

,Author,1,Content,FactLevel
0,Facebook posts,"November 6, 2020 in a Facebook post",“The NAACP has received credible information ...,false
1,Facebook posts,"November 5, 2020 in an Instagram post",An election worker in Georgia threw away a ba...,false
2,Tweets,"November 5, 2020 in a tweet","A list shows over 14,000 dead people voted in...",false
3,Nevada Republican Party,"November 5, 2020 in a tweet","Republicans in Nevada found “at least 3,062 i...",false
4,Ted Cruz,"November 5, 2020 in a Fox News interview",Philadelphia is “clouding the vote counting i...,false

In [34]:
df1 = data1['1'].str.split(r" in ", n = 1, expand=True)
data1['Date'] = df1[0]
data1.head(5)

,Author,1,Content,FactLevel,Date
0,Facebook posts,"November 6, 2020 in a Facebook post",“The NAACP has received credible information ...,false,"November 6, 2020"
1,Facebook posts,"November 5, 2020 in an Instagram post",An election worker in Georgia threw away a ba...,false,"November 5, 2020"
2,Tweets,"November 5, 2020 in a tweet","A list shows over 14,000 dead people voted in...",false,"November 5, 2020"
3,Nevada Republican Party,"November 5, 2020 in a tweet","Republicans in Nevada found “at least 3,062 i...",false,"November 5, 2020"
4,Ted Cruz,"November 5, 2020 in a Fox News interview",Philadelphia is “clouding the vote counting i...,false,"November 5, 2020"

In [44]:
df2 = data1['1'].str.split(r", ",n=1, expand=True)
data1['Occasion'] = df2[1].astype('str').apply(lambda x: x[8:])

,Author,1,Content,FactLevel,Date,Occasion
0,Facebook posts,"November 6, 2020 in a Facebook post",“The NAACP has received credible information ...,false,"November 6, 2020",a Facebook post
1,Facebook posts,"November 5, 2020 in an Instagram post",An election worker in Georgia threw away a ba...,false,"November 5, 2020",an Instagram post
2,Tweets,"November 5, 2020 in a tweet","A list shows over 14,000 dead people voted in...",false,"November 5, 2020",a tweet
3,Nevada Republican Party,"November 5, 2020 in a tweet","Republicans in Nevada found “at least 3,062 i...",false,"November 5, 2020",a tweet
4,Ted Cruz,"November 5, 2020 in a Fox News interview",Philadelphia is “clouding the vote counting i...,false,"November 5, 2020",a Fox News interview
...,...,...,...,...,...,...
927,Bloggers,"November 29, 2019 in an article",Says the New York Times reported that Hillary...,false,"November 29, 2019",an article
928,Doug Collins,"December 18, 2019 in an opening statement to t...","""In November 2019, Speaker Pelosi said it wou...",false,"December 18, 2019",an opening statement to the House of Represent...
929,Barry Loudermilk,"December 18, 2019 in remarks on the House floor","""When Jesus was falsely accused of treason, P...",false,"December 18, 2019",remarks on the House floor
930,Viral image,"December 15, 2019 in a Facebook post",An old image shows a drug store with a mariju...,false,"December 15, 2019",a Facebook post
931,Viral image,"November 8, 2019 in a Facebook post","""Yesterday Virginia announced the end of yout...",false,"November 8, 2019",a Facebook post

In [46]:
data1 = data1.drop(columns=['1'])

,Author,Content,FactLevel,Date,Occasion
0,Facebook posts,“The NAACP has received credible information ...,false,"November 6, 2020",a Facebook post
1,Facebook posts,An election worker in Georgia threw away a ba...,false,"November 5, 2020",an Instagram post
2,Tweets,"A list shows over 14,000 dead people voted in...",false,"November 5, 2020",a tweet
3,Nevada Republican Party,"Republicans in Nevada found “at least 3,062 i...",false,"November 5, 2020",a tweet
4,Ted Cruz,Philadelphia is “clouding the vote counting i...,false,"November 5, 2020",a Fox News interview
...,...,...,...,...,...
927,Bloggers,Says the New York Times reported that Hillary...,false,"November 29, 2019",an article
928,Doug Collins,"""In November 2019, Speaker Pelosi said it wou...",false,"December 18, 2019",an opening statement to the House of Represent...
929,Barry Loudermilk,"""When Jesus was falsely accused of treason, P...",false,"December 18, 2019",remarks on the House floor
930,Viral image,An old image shows a drug store with a mariju...,false,"December 15, 2019",a Facebook post
931,Viral image,"""Yesterday Virginia announced the end of yout...",false,"November 8, 2019",a Facebook post

In [61]:
wholepath = ParentPath + '\\' + 'false.csv'
data2 = pd.read_csv(wholepath)
data2.head()

,Unnamed: 0,Author,Content,FactLevel,Occasion
0,0,Facebook posts,“The NAACP has received credible information ...,false,a Facebook post
1,1,Facebook posts,An election worker in Georgia threw away a ba...,false,an Instagram post
2,2,Tweets,"A list shows over 14,000 dead people voted in...",false,a tweet
3,3,Nevada Republican Party,"Republicans in Nevada found “at least 3,062 i...",false,a tweet
4,4,Ted Cruz,Philadelphia is “clouding the vote counting i...,false,a Fox News interview

In [62]:
factlevel = ['false', 'half-true', 'mostly-false', 'mostly-true', 'pants-fire', 'true']

In [63]:
for i in range(len(factlevel)):
    wholepath = ParentPath + '\\' + factlevel[i] + '.csv'
    data = pd.read_csv(wholepath)
    print(factlevel[i])
    print(data.shape)

false
(932, 5)
half-true
(240, 5)
mostly-false
(270, 5)
mostly-true
(180, 5)
pants-fire
(360, 5)
true
(150, 5)

In [64]:
932+240+270+180+360+150

2132

In [65]:
wholepath = ParentPath + '\\' + factlevel[0] + '.csv'
false = pd.read_csv(wholepath)
false['Author'].value_counts()

Facebook posts             388
Viral image                160
Donald Trump                69
Bloggers                    50
Instagram posts             22
                          ...
Better Future Michigan       1
Eric Trump                   1
Snoop Dogg                   1
Rudy Giuliani                1
Joy Behar                    1
Name: Author, Length: 173, dtype: int64

In [66]:
wholepath = ParentPath + '\\' + 'pants-fire' + '.csv'
pf = pd.read_csv(wholepath)
pf['Author'].value_counts()

Facebook posts                            138
Viral image                                72
Bloggers                                   46
Donald Trump                               38
Tweets                                      9
Instagram posts                             8
YouTube videos                              5
Donald Trump Jr.                            3
Joe Biden                                   2
Paul Maner                                  1
Robocaller                                  1
Nancy Pelosi                                1
Rush Limbaugh                               1
Mitch McConnell                             1
Kevin McCarthy                              1
Joe Sanfelippo                              1
Kathy Hochul                                1
Committee to Defend the President           1
Steve Scalise                               1
MacIver Institute                           1
Sherill Sellman                             1
TikTok posts                                1
Charlie Kirk                                1
Tucker Carlson                              1
Kayleigh McEnany                            1
Conservative-Daily                          1
Louie Gohmert                               1
Li-Meng Yan                                 1
Ron DeSantis                                1
Mike Pence                                  1
Emails                                      1
William Barr                                1
Paul Gosar                                  1
Jeff Shipley                                1
Leaders for a Better Community              1
Brian Westrate                              1
David A. Clarke Jr.                         1
Republican State Leadership Committee       1
Todd Starnes                                1
Gae Magnafici                               1
Nikki Haley                                 1
Darin LaHood                                1
Tom Tiffany                                 1
One America News                            1
Dan Patrick                                 1
Martha McSally                              1
MSNBC                                       1
Alex Jones                                  1
Name: Author, dtype: int64

In [67]:
wholepath = ParentPath + '\\' + 'mostly-false' + '.csv'
mf = pd.read_csv(wholepath)
mf['Author'].value_counts()

Facebook posts        71
Donald Trump          29
Viral image           18
Joe Biden             10
Bloggers               9
                      ..
Mandela Barnes         1
Martha McSally         1
Adam Schnelting        1
Alex Azar              1
Michael Bloomberg      1
Name: Author, Length: 112, dtype: int64